### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [Story-Chief/craft-cms-module-storychief-v3#5]
When installing this plugin with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `storychief\storychiefv3\storychief\FieldTypes\AssetsStoryChiefFieldType` located in `./vendor/storychief/storychief-v3/src/StoryChief/FieldTypes/AssetsStoryChiefFieldType.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

To fix, run the following command:

```bash
> git mv src/StoryChief src/storychief
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by sweet-greg** [comment]
Thanks for bringing this to our attention. We fixed it with release v1.0.7

**Comment by brandonkelly** [comment]
Thank you :)

**Comment by brandonkelly** [comment]
This isn’t fully resolved yet. I just tried installing `storychief/craft-cms-v3-storychief:dev-master` (your `master` branch), and now getting this deprecation notice:

> Deprecation Notice: Class `storychief\storychiefv3\helpers\StoryChiefHelper` located in `./vendor/storychief/craft-cms-v3-storychief/src/storychief/Helpers/StoryChiefHelper.php` does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

So the fix in this case is more involved than my original issue suggested, sorry. Please take a little time to make sure that your namespaces & class names perfectly match the folder/filenames, including their casing, otherwise they won’t load for anyone running Composer 2.

**Comment by brandonkelly** [comment]
Also, looks like you tagged version 1.0.7, but you didn’t update the version number in `composer.json`, so the update isn’t getting picked up.

**Comment by sweet-greg** [comment]
Sorry about that @brandonkelly 
Fixed the namespacing issue and released 1.0.8
